### ISSUE TITLE
Hm9000

### ISSUE THREAD

**Issue by lyuyun** [cloudfoundry/hm9000#17]
i got dmesg info as below:

![image](https://cloud.githubusercontent.com/assets/6880843/9467912/5531b8ae-4b71-11e5-83f3-75620f5eb0b8.png)

**Comment by Amit-PivotalLabs** [comment]
Please provide an informative title and a detailed description of the problem you're experiencing.  Do you have a CF deployment that's failing?  What's the failure? What version of CF, stemcell, etc.  Or were you just exploring and were concerned about the "Tainted" string in the dmesg output?  If so, what is your particular concern?
