### ISSUE TITLE
slave hm9000_api_server stops listening on port 5155

### ISSUE THREAD

**Issue by rwwohl** [cloudfoundry/hm9000#18]
After upgrading to cf v235, we noticed that 'cf apps' calls would show ? in the instance counts periodically.  Looks like when running 2 hm9000's, only one of hm9000_api_server instances will have port 5155 listening.  If gorouter sends them to the one not listening, logs an error and you get back all ? on your app instance states.  Talking to devs in cf slack channel they indicated this is an issue and both hm9000_api_server instances should be always listening on port 5155.

**Comment by fraenkel** [comment]
Known issue that has been fixed in CF v237
