### ISSUE TITLE
Actual state save timeout in Listener

### ISSUE THREAD

**Issue by JimmyMa** [cloudfoundry/hm9000#19]
The Listener logs has below error almost every 20 seconds:
{"timestamp":1463115787.966745853,"process_id":23237,"source":"vcap.hm9000.listener","log_level":"info","message":"Saving Heartbeats - {\"Heartbeats to Save\":\"46\"}","data":null}
{"timestamp":1463116020.814734697,"process_id":23237,"source":"vcap.hm9000.listener","log_level":"info","message":"Save took too long.  Not bumping freshness.","data":null}

The cause is that the duration of ensureCacheIsReady (which is 20 seconds interval) is counted in the duration of SyncHeartbeats, that causes actual state timeout.

https://github.com/cloudfoundry/hm9000/blob/master/store/actual_state.go#L42

**Comment by fraenkel** [comment]
We have made improvements to use etcd less which should improve the overall etcd usage. The code has been not been delivered to CF release but will be shortly.
