### ISSUE TITLE
'?' is displayed in a 'instances' column of cf app command result

### ISSUE THREAD

**Issue by MNitta** [cloudfoundry/hm9000#20]
'?' is displayed in a 'instances' column of cf app command result, if 2 or more than 2 HM9000 instances are running. This happens sporadically, not always. I think this is caused by the following reason:

Only one api server of HM9000 runs when 2 or more than 2 instances of HM9000 are deployed. 
However, registrar always runs in each HM9000 instance. Therefore, all routes of api server are registered to Go Router. Therefore, there are possibilities that the bulk api requests are routed to a stopping api server.

**Comment by fraenkel** [comment]
What release of CF are you using? This was a known issue and fixed in v237.

**Comment by MNitta** [comment]
Thank you for your reply. I am using v235. I'll check this problem occurs or not in v237.

**Comment by fraenkel** [comment]
I will close this for now but you can reopen it if it is still an issue.
