### ISSUE TITLE
removing store

### ISSUE THREAD

**Issue by abonillasuse** [cloudfoundry/hm9000#21]
There is a comment about 

"Delete (or move) the etcd storage directory located under /var/vcap/store"

but if this is done, etcd wont start again.

2016/08/18 03:52:26 etcdserver: create snapshot directory error: mkdir /var/vcap/store/etcd: permission denied

perhaps instead say to remove the content in the snap and wal folders? Or perhaps the real bug is in the permissions?

bosh_etqu6msmw@3f6cd1d9-a2b9-489f-8e9f-6e573d7072ea:~$ ls -l /var/vcap/
total 40
drwx------ 9 root root 4096 Aug 16 04:59 bosh
drwxr-xr-x 5 root root 4096 Aug 18 03:59 bosh_ssh
drwxr-xr-x 8 root root 4096 Aug 16 05:12 data
drwxr-xr-x 2 root root 4096 Aug 16 04:59 instance
drwxr-xr-x 2 root root 4096 Aug 16 05:12 jobs
drwxr-xr-x 2 root root 4096 Jun 28 23:00 micro
drwxr-xr-x 3 root root 4096 Jun 28 22:44 micro_bosh
drwxr-xr-x 5 root root 4096 Aug 16 05:13 monit
drwxr-xr-x 2 root root 4096 Aug 16 05:12 packages
drwxr-xr-x 4 root root 4096 Aug 18 03:56 store
lrwxrwxrwx 1 root root   18 Jun 28 22:44 sys -> /var/vcap/data/sys
bosh_etqu6msmw@3f6cd1d9-a2b9-489f-8e9f-6e573d7072ea:~$ ls -l /var/vcap/store/
total 20
drwxr-xr-x 3 vcap vcap  4096 Aug 16 05:13 etcd
drwx------ 2 root root 16384 Aug 16 05:12 lost+found
bosh_etqu6msmw@3f6cd1d9-a2b9-489f-8e9f-6e573d7072ea:~$ ls -l /var/vcap/store/etcd/
total 4
drwx------ 4 vcap vcap 4096 Aug 16 05:13 member
bosh_etqu6msmw@3f6cd1d9-a2b9-489f-8e9f-6e573d7072ea:~$ ls -l /var/vcap/store/etcd/member/
ls: cannot open directory /var/vcap/store/etcd/member/: Permission denied
bosh_etqu6msmw@3f6cd1d9-a2b9-489f-8e9f-6e573d7072ea:~$ sudo ls -l /var/vcap/store/etcd/member/
total 8
drwx------ 2 vcap vcap 4096 Aug 18 03:55 snap
drwx------ 2 vcap vcap 4096 Aug 18 03:57 wal

**Comment by fraenkel** [comment]
You can see [Disaster Recovery](https://github.com/cloudfoundry-incubator/etcd-release#disaster-recovery) which is the documented way from the etcd-release.
If that doesn't work any more, I would open an issue there.

I will update our README to just point there.
