### ISSUE TITLE
hm9000_analyzer occasionally causes "monit status" to break

### ISSUE THREAD

**Issue by pusherofbrooms** [cloudfoundry/hm9000#23]
Occasionally, "monit status" on an hm9000 instance will return a failed status instead of detailed process status. This is resolved by restarting the hm9000_analyzer process. I assume this process is occasionally returning something that monit can't handle.

This problem cascades into bosh where "bosh vms DEPLOYMENT" will return an error related to monit. Once hm9000_analyzer is restarted on the offending instance, "bosh vms DEPLOYMENT" will return the list of vms as it should.

**Comment by fraenkel** [comment]
This isn't an hm9000 issue but a BOSH issue. There is no interaction between processes and BOSH other than exiting.
You would need to provide more detailed logs to understand what the offending issue is.  Please reopen when you have more detailed information.

**Comment by pusherofbrooms** [comment]
This seems to be due to an interaction between hm9000_analyzer and monit. Somehow, when monit tries to retrieve status from this process, it is failing in a way that causes monit to break. hm9000_analyzer is still running in this case. I would disagree that it is a bosh issue in general.

Maybe bosh has another bug in how it handles monit failures, but that's not what I'm referring to here.

**Comment by fraenkel** [comment]
There is nothing special here. This process is no different than any other Go process. Unless you show monit logs, I don't know how to help you.
The fact that the process is running would point to a monit issue. Monit is provided and managed by BOSH which is why I am deferring to them.
