### ISSUE TITLE
Failed to handle app.state request - Error:App not found

### ISSUE THREAD

**Issue by lyuyun** [cloudfoundry/hm9000#7]
I do ’cf unmap-route APP DOMAIN‘, then send 'cf apps' to get app info, but get incorrect result of '0/1 instances'.

I found error logs as follow below in hm9000_api_server.stdout.log:
{"timestamp":1400189188.394666433,"process_id":21551,"source":"vcap.hm9000.api_server","log_level":"error","message":"Failed to handle app.state request - Error:App not found - {\"elapsed time\":\"2.621651ms\",\"payload\":\"{\\"droplet\\":\\"08d86b67-d3b1-4e21-991a-5add5ba5fc9d\\",\\"version\\":\\"f5a8bfb4-561b-4415-8f6a-7d48d8f7964c\\"}\"}","data":null}

**Comment by dieucao** [comment]
@lyuyun I'd recommend updating to the latest cf release version v195.  I believe this issue has been fixed.
